SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `broadsheet`;
create table broadsheet (id int(11) NOT NULL AUTO_INCREMENT, name tinytext, class varchar(5), 
en_cat int(11) NOT NULL DEFAULT '0', en_exam int(11) NOT NULL DEFAULT '0', en_total int(11) as (en_cat + en_exam),
mt_cat int(11) NOT NULL DEFAULT '0', mt_exam int(11) NOT NULL DEFAULT '0', mt_total int(11) as (mt_cat + mt_exam),
bt_cat int(11) NOT NULL DEFAULT '0', bt_exam int(11) NOT NULL DEFAULT '0', bt_total int(11) as (bt_cat + bt_exam),
bu_cat int(11) NOT NULL DEFAULT '0', bu_exam int(11) NOT NULL DEFAULT '0', bu_total int(11) as (bu_cat + bu_exam),
bs_cat int(11) NOT NULL DEFAULT '0', bs_exam int(11) NOT NULL DEFAULT '0', bs_total int(11) as (bs_cat + bs_exam),
ss_cat int(11) NOT NULL DEFAULT '0', ss_exam int(11) NOT NULL DEFAULT '0', ss_total int(11) as (ss_cat + ss_exam),
ag_cat int(11) NOT NULL DEFAULT '0', ag_exam int(11) NOT NULL DEFAULT '0', ag_total int(11) as (ag_cat + ag_exam),
is_cat int(11) NOT NULL DEFAULT '0', is_exam int(11) NOT NULL DEFAULT '0', is_total int(11) as (is_cat + is_exam),
al_cat int(11) NOT NULL DEFAULT '0', al_exam int(11) NOT NULL DEFAULT '0', al_total int(11) as (al_cat + al_exam),
qs_cat int(11) NOT NULL DEFAULT '0', qs_exam int(11) NOT NULL DEFAULT '0', qs_total int(11) as (qs_cat + qs_exam),
ph_cat int(11) NOT NULL DEFAULT '0', ph_exam int(11) NOT NULL DEFAULT '0', ph_total int(11) as (ph_cat + ph_exam),
fr_cat int(11) NOT NULL DEFAULT '0', fr_exam int(11) NOT NULL DEFAULT '0', fr_total int(11) as (fr_cat + fr_exam),
ca_cat int(11) NOT NULL DEFAULT '0', ca_exam int(11) NOT NULL DEFAULT '0', ca_total int(11) as (ca_cat + ca_exam),
yo_cat int(11) NOT NULL DEFAULT '0', yo_exam int(11) NOT NULL DEFAULT '0', yo_total int(11) as (yo_cat + yo_exam),
ci_cat int(11) NOT NULL DEFAULT '0', ci_exam int(11) NOT NULL DEFAULT '0', ci_total int(11) as (ci_cat + ci_exam),
he_cat int(11) NOT NULL DEFAULT '0', he_exam int(11) NOT NULL DEFAULT '0', he_total int(11) as (he_cat + he_exam),
it_cat int(11) NOT NULL DEFAULT '0', it_exam int(11) NOT NULL DEFAULT '0', it_total int(11) as (it_cat + it_exam),
pu_cat int(11) NOT NULL DEFAULT '0', pu_exam int(11) NOT NULL DEFAULT '0', pu_total int(11) as (pu_cat + pu_exam),
ne_cat int(11) NOT NULL DEFAULT '0', ne_exam int(11) NOT NULL DEFAULT '0', ne_total int(11) as (ne_cat + ne_exam),
ho_cat int(11) NOT NULL DEFAULT '0', ho_exam int(11) NOT NULL DEFAULT '0', ho_total int(11) as (ho_cat + ho_exam),
po_cat int(11) NOT NULL DEFAULT '0', po_exam int(11) NOT NULL DEFAULT '0', po_total int(11) as (po_cat + po_exam),
lt_cat int(11) NOT NULL DEFAULT '0', lt_exam int(11) NOT NULL DEFAULT '0', lt_total int(11) as (lt_cat + lt_exam),
sp_cat int(11) NOT NULL DEFAULT '0', sp_exam int(11) NOT NULL DEFAULT '0', sp_total int(11) as (sp_cat + sp_exam),
wr_cat int(11) NOT NULL DEFAULT '0', wr_exam int(11) NOT NULL DEFAULT '0', wr_total int(11) as (wr_cat + wr_exam),
hl_cat int(11) NOT NULL DEFAULT '0', hl_exam int(11) NOT NULL DEFAULT '0', hl_total int(11) as (hl_cat + hl_exam),
rw_cat int(11) NOT NULL DEFAULT '0', rw_exam int(11) NOT NULL DEFAULT '0', rw_total int(11) as (rw_cat + rw_exam),
at_cat int(11) NOT NULL DEFAULT '0', at_exam int(11) NOT NULL DEFAULT '0', at_total int(11) as (at_cat + at_exam),
pe_cat int(11) NOT NULL DEFAULT '0', pe_exam int(11) NOT NULL DEFAULT '0', pe_total int(11) as (pe_cat + pe_exam),
aw_cat int(11) NOT NULL DEFAULT '0', aw_exam int(11) NOT NULL DEFAULT '0', aw_total int(11) as (aw_cat + aw_exam),
cat_total int(11) as (en_cat + mt_cat + bt_cat + bu_cat + bs_cat + ss_cat + ag_cat  + is_cat + al_cat + qs_cat + ph_cat + fr_cat + ca_cat + yo_cat + ci_cat + he_cat + it_cat),
exam_total int(11) as (en_exam + mt_exam + bt_exam + bu_exam + bs_exam + ss_exam + ag_exam  + is_exam + al_exam + qs_exam + ph_exam + fr_exam + ca_exam + yo_exam + ci_exam + he_exam + it_exam),
PRIMARY KEY (`id`));
insert into broadsheet (id, name, class, en_cat, en_exam, mt_cat, mt_exam, bs_cat, bs_exam, bt_cat, bt_exam, bu_cat, bu_exam, ss_cat, ss_exam, ag_cat, ag_exam, is_cat, is_exam, al_cat, al_exam, qs_cat, qs_exam, ph_cat, ph_exam, fr_cat, fr_exam, ca_cat, ca_exam, yo_cat, yo_exam, ci_cat, ci_exam, he_cat, he_exam, it_cat, it_exam) values(1, 'Yusuf Rodiyyah', 'JS1', 28,51, 38,53, 39,51, 40,60, 40,60, 37,49, 37,56, 37,56, 40,60, 39,58, 35,60, 39,58, 37,50, 35,60, 55,39, 55,37, 55,39);

-- ALTER TABLE `broadsheet`
-- ADD `pu_cat` int(11) NOT NULL;

-- To sum up per student add the ca, exam, totals inside the broadsheet table
-- Also update the psychomotor
-- Lastly, create a 17 subject total of avg and max in gen_score table 


INSERT into gen_score (`class`, `value`) VALUES
('JS1', 'en_avg'),
('JS1', 'en_max'),
('JS1', 'mt_avg'),
('JS1', 'mt_max'),
('JS1', 'bt_avg'),
('JS1', 'bt_max'),
('JS1', 'bu_avg'),
('JS1', 'bu_max'),
('JS1', 'bs_avg'),
('JS1', 'bs_max'),
('JS1', 'ss_avg'),
('JS1', 'ss_max'),
('JS1', 'ag_avg'),
('JS1', 'ag_max'),
('JS1', 'is_avg'),
('JS1', 'is_max'),
('JS1', 'al_avg'),
('JS1', 'al_max'),
('JS1', 'qs_avg'),
('JS1', 'qs_max'),
('JS1', 'ph_avg'),
('JS1', 'ph_max'),
('JS1', 'fr_avg'),
('JS1', 'fr_max'),
('JS1', 'ca_avg'),
('JS1', 'ca_max'),
('JS1', 'yo_avg'),
('JS1', 'yo_max'),
('JS1', 'ci_avg'),
('JS1', 'ci_max'),
('JS1', 'he_avg'),
('JS1', 'he_max'),
('JS1', 'it_avg'),
('JS1', 'it_max'),
('JS2', 'en_avg'),
('JS2', 'en_max'),
('JS2', 'mt_avg'),
('JS2', 'mt_max'),
('JS2', 'bt_avg'),
('JS2', 'bt_max'),
('JS2', 'bu_avg'),
('JS2', 'bu_max'),
('JS2', 'bs_avg'),
('JS2', 'bs_max'),
('JS2', 'ss_avg'),
('JS2', 'ss_max'),
('JS2', 'ag_avg'),
('JS2', 'ag_max'),
('JS2', 'is_avg'),
('JS2', 'is_max'),
('JS2', 'al_avg'),
('JS2', 'al_max'),
('JS2', 'qs_avg'),
('JS2', 'qs_max'),
('JS2', 'ph_avg'),
('JS2', 'ph_max'),
('JS2', 'fr_avg'),
('JS2', 'fr_max'),
('JS2', 'ca_avg'),
('JS2', 'ca_max'),
('JS2', 'yo_avg'),
('JS2', 'yo_max'),
('JS2', 'ci_avg'),
('JS2', 'ci_max'),
('JS2', 'he_avg'),
('JS2', 'he_max'),
('JS2', 'it_avg'),
('JS2', 'it_max'),
('JS3', 'en_avg'),
('JS3', 'en_max'),
('JS3', 'mt_avg'),
('JS3', 'mt_max'),
('JS3', 'bt_avg'),
('JS3', 'bt_max'),
('JS3', 'bu_avg'),
('JS3', 'bu_max'),
('JS3', 'bs_avg'),
('JS3', 'bs_max'),
('JS3', 'ss_avg'),
('JS3', 'ss_max'),
('JS3', 'ag_avg'),
('JS3', 'ag_max'),
('JS3', 'is_avg'),
('JS3', 'is_max'),
('JS3', 'al_avg'),
('JS3', 'al_max'),
('JS3', 'qs_avg'),
('JS3', 'qs_max'),
('JS3', 'ph_avg'),
('JS3', 'ph_max'),
('JS3', 'fr_avg'),
('JS3', 'fr_max'),
('JS3', 'ca_avg'),
('JS3', 'ca_max'),
('JS3', 'yo_avg'),
('JS3', 'yo_max'),
('JS3', 'ci_avg'),
('JS3', 'ci_max'),
('JS3', 'he_avg'),
('JS3', 'he_max'),
('JS3', 'it_avg'),
('JS3', 'it_max'),